### ISSUE TITLE
Google Sheets URL Submission

### ISSUE THREAD

**Issue by aldoportillo** [DPI-WE/database-architecture-todo-list#1]
@heratyian there is an issue in the block below

```markdown

![](assets/anyone-with-link.png)

- Enter your `docs.google.com/spreadsheets` shared URL:
- `docs.google.com/spreadsheets`
  - Great job!
- any
  - Not quite. Make sure the URL looks like: `docs.google.com/spreadsheets`
{: .free_text #github_profile_url title="GitHub profile URL" points="1" answer="1" }
```

Trainees are adding their URL and it returns the Not quite error. Only the `docs.google.com/spreadsheets` answer is working.

**Comment by heratyian** [comment]
@marywebby can you change this to a yes/no question? Url submissions are not working.

**Comment by heratyian** [comment]
Example https://github.com/DPI-WE/writing-functional-requirements/blob/main/content.md

**Comment by heratyian** [comment]
https://github.com/DPI-WE/database-architecture-todo-list/commit/605565b81d2fc939dd457ee03117505614f3e18f
